import{n as f}from"./assets/vendor-BY9c7rfI.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const d of i.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(e){if(e.ep)return;e.ep=!0;const i=o(e);fetch(e.href,i)}})();const l={form:document.querySelector(".header-form"),taskList:document.querySelector("#task-list"),themeToggle:document.querySelector("#themeToggle")};function m(s){const t=s.map(({id:o,title:n,description:e})=>`
        <li class="task-list-item" id="${o}">
          <button class="task-list-item-btn"
          type="button"
          data-id="${o}">Delete</button>
          <h3>${n}</h3>
          <p>${e}</p>
        </li>
      `).join("");l.taskList.innerHTML=t}const a={tasks:"tasks",theme:"theme"};function c(s,t){localStorage.setItem(s,JSON.stringify(t))}function u(s){const t=localStorage.getItem(s);return t?JSON.parse(t):null}let r=u(a.tasks)||[];function h(s){s.preventDefault();const t=s.target.elements.taskName.value.trim(),o=s.target.elements.taskDescription.value.trim();if(t===""||o===""){alert("Fill in all fields!");return}const n={id:f(),title:t,description:o};r.push(n),m(r),c(a.tasks,r),s.target.reset()}function g(s){if(!s.target.classList.contains("task-list-item-btn"))return;const t=s.target.closest("li").id;console.log(t),r=r.filter(o=>o.id!==t),m(r),c(a.tasks,r)}function p(){m(r)}function k(){document.body.classList.contains("theme-dark")?(document.body.classList.add("theme-light"),document.body.classList.remove("theme-dark"),c(a.theme,"light")):(document.body.classList.add("theme-dark"),document.body.classList.remove("theme-light"),c(a.theme,"dark"))}function y(){u(a.theme)==="light"&&(document.body.classList.add("theme-light"),document.body.classList.remove("theme-dark"))}p();y();l.form.addEventListener("submit",h);l.taskList.addEventListener("click",g);l.themeToggle.addEventListener("click",k);
//# sourceMappingURL=index.js.map
